fix(ansible): Adding bios config job and reboot tasks in bios.yml
opiproject/lab pull request #40
Opened 2024-07-08 12:01 UTC by rahulsachdev

2024-07-08 18:11 UTC, glimchb commented on ansible/bios.yml
> +      when: inventory_hostname == 'dh1bmc'
remove `when` here and rename the task from `serial`

2024-07-08 18:12 UTC, glimchb commented on ansible/bios.yml
> +      when: inventory_hostname == 'dh1bmc'
I think we should use another condition here
In previous task or from gather_facts we can already know if we talking to iDRAC or not
let's use that as a condition

2024-07-08 18:15 UTC, glimchb commented on ansible/bios.yml
> +      when: inventory_hostname == 'dh1bmc'
two `when` statements ? one here and another one below `bios_config_job.changed`

2024-07-08 18:15 UTC, glimchb requested changes
2 when statements

2024-07-09 22:13 UTC, glimchb commented on ansible/bios.yml
> +        #ansible.builtin.debug: msg={{ result.redfish_facts.bios_attribute.entries[0][1].SystemManufacturer }}
this is a good debug line to keep uncommented
all the rest comments should be removed

2024-07-09 22:13 UTC, glimchb commented on ansible/bios.yml
> +        #      tags: ["TEST"]
remove this line

2024-07-09 22:13 UTC, glimchb commented on ansible/bios.yml
> +      when: result.redfish_facts.bios_attribute.entries[0][1].SystemManufacturer is defined and result.redfish_facts.bios_attribute.entries[0][1].SystemManufacturer == "Dell Inc." and bios_attribute.
let's split into lines like
https://github.com/opiproject/lab/blob/dabdb551b0f0f0188206114af003ad8d9577bb3a/ansible/monitoring.yml#L72-L76

2024-07-09 22:13 UTC, glimchb reviewed
Much better!!!
few small suggestions inside
and please squash all the commits to a single one

2024-07-12 10:04 UTC, closed without merging

2024-07-12 10:04 UTC, rahulsachdev commented
Will work on Boris's suggestions and submit a new PR