feat: Adding mrv and amd
opiproject/lab pull request #52
Opened 2024-08-21 12:08 UTC by mohamedasifs123

2024-08-30 20:10 UTC, sandersms commented
@mohamedasifs123 Please correct the failing required CI checks so the PR can be reviewed.

2024-09-11 21:02 UTC, glimchb requested changes
marvell and amd cards are not in the inventory....
not sure I understand how this PR works...

2024-09-11 21:34 UTC, sandersms commented
@mohamedasifs123 You will need to update your project to pick up the latest changes with resolve the docker-lint issue that Boris checked in here and in the CI processing.

2024-09-13 01:03 UTC, mohamedasifs123 commented
> marvell and amd cards are not in the inventory....
> not sure I understand how this PR works...

https://github.com/opiproject/lab/blob/main/ansible%2Finventory#L18
I think amd and mrv is present on inventory under DPUs.

2024-09-13 01:10 UTC, mohamedasifs123 commented
> @mohamedasifs123 You will need to update your project to pick up the latest changes with resolve the docker-lint issue that Boris checked in here and in the CI processing.

I have not modified or added the dockerfile.The error show no dockerfiles found

2024-09-18 16:00 UTC, sandersms commented
> > @mohamedasifs123 You will need to update your project to pick up the latest changes with resolve the docker-lint issue that Boris checked in here and in the CI processing.
> 
> I have not modified or added the dockerfile.The error show no dockerfiles found

The new changes are a check on whether to run the docker-lint or not.  In the case of this repository we don't run the docker-lint and that is the change in the files that need to be picked up in your changes.

2024-10-11 20:48 UTC, glimchb commented
This code is not working. Both cards are down

2025-02-10 01:45 UTC, closed without merging