Merge reboot tasks for both iLO and iDRAC into a single task
opiproject/lab pull request #62
Opened 2024-10-02 00:23 UTC by Sakethanne

Merge reboot tasks for both iLO and iDRAC into a single task

2024-10-02 20:04 UTC, glimchb commented
@Sakethanne can you leave only 1 commit in this PR ?

https://github.com/opiproject/lab/pull/62/commits/b27a13bc5b933c5a3e8e3d5e93adf4db08963545

linters and md files do not belong here

2024-10-02 20:06 UTC, glimchb requested changes
@Sakethanne can you leave only 1 commit in this PR ?

https://github.com/opiproject/lab/pull/62/commits/b27a13bc5b933c5a3e8e3d5e93adf4db08963545

linters and md files do not belong here

2024-10-02 20:11 UTC, glimchb approved these changes

2024-10-02 20:16 UTC, glimchb commented on ansible/bios.yml
> +          (inventory_hostname in ['dh2bmc', 'dh3bmc'] and bios_attribute.changed)
I don't understand this `or`

2024-10-02 20:28 UTC, glimchb requested changes
inline question about `or`

2024-10-02 23:41 UTC, Sakethanne commented on ansible/bios.yml
> +          (inventory_hostname in ['dh2bmc', 'dh3bmc'] and bios_attribute.changed)
the `bios_attribute.changed ` will effectively only change if the bios attributes on HP systems change, and `bios_config.changed` will be effected only if the bios settings change on Dell Systems even though the `bios_attribute` has been changed.

Instead of the complex condition earlier, we can modify that to this

`bios_config_job.changed or bios_attribute.changed`

as this will cover all the bases

2024-10-03 12:38 UTC, glimchb approved these changes
Looks better

2024-10-03 12:39 UTC, merged