Added ansible scripts to install Ubuntu Auto Install OS on Dell servers
opiproject/lab pull request #90
Opened 2024-12-04 02:01 UTC by Sakethanne

Added ansible scripts to install Ubuntu Auto Install OS on Dell servers

2024-12-05 12:05 UTC, glimchb commented on ansible/install_os.yml
> +      when: user_input.user_input | length == 0
no prompts please, everything is via configs and arguments only

2024-12-05 12:07 UTC, glimchb commented on ansible/install_os.yml
> +
why not simple
```
when:
        - inventory_hostname == 'dh2bmc' or inventory_hostname == 'dh3bmc'
```

2024-12-05 12:08 UTC, glimchb commented on ansible/os_install/dell_os_install.yml
> +- name: Install Ubuntu OS using ISO
no new sub-folders please! flat tree

2024-12-05 12:08 UTC, glimchb requested changes
inline

2024-12-05 23:38 UTC, Sakethanne commented
Fixed the scripts as per the all the suggestions

2024-12-06 23:19 UTC, glimchb commented on ansible/dell_os_install.yml
> +- name: Debug IDRAC credentials
can you just copy from https://github.com/opiproject/lab/blob/main/ansible/monitoring.yml ?

```
- name: OS Installation
  hosts: dh1bmc,dh4bmc
  become: true
  vars:
    ...
  tasks:
	- name: Install Ubuntu OS using ISO
	  ansible.builtin.import_role:
		name: dellemc.openmanage.idrac_os_deployment
	  vars:
		hostname: "{{ ansible_host }}"
		username: "{{ idrac_user }}"
		password: "{{ ansible_password }}"
		os_name: RHEL
		os_version: 9
		source:
		  protocol: http
		  hostname: "{{ ip_address }}"
		  iso_path: ""
		  iso_name: "{{ ubuntu_iso }}"
		  is_custom_iso: true
```
?

2024-12-06 23:19 UTC, glimchb commented on ansible/install_os.yml
> +  hosts: hostbmcs
why do we need this file ?

2024-12-08 22:58 UTC, glimchb commented on ansible/install_os.yml
> +  hosts: hostbmcs
Can you just put here dh1bm,dh4bmc ? 
and avoid all switch cases later in the code ?

2024-12-08 22:59 UTC, glimchb commented on ansible/install_os.yml
> +    ip_address: "172.22.0.1"
Instead of cost hard coded ip here, can you use mgmt from inventory?

2024-12-08 22:59 UTC, glimchb commented on ansible/install_os.yml
> +      ansible.builtin.uri:
Do you need to find url every time ? Isn’t it fixed for dell ? Show me what this returns…

2024-12-08 23:01 UTC, glimchb commented on ansible/install_os.yml
> +            url: "https://{{ ansible_host }}{{ idrac_osd_service_url }}/Actions/DellOSDeploymentService.DetachISOImage"
Why you using raw url ? Isn’t attach and detach part of redfish or dell collection already?

2024-12-08 23:01 UTC, glimchb commented on ansible/install_os.yml
> +        name: dellemc.openmanage.idrac_os_deployment
Why import role ? And not hust call a role here ?

2024-12-08 23:30 UTC, Sakethanne commented on ansible/install_os.yml
> +        name: dellemc.openmanage.idrac_os_deployment
This is due to the ansible-lint check, when I use the role directly, I need to rename the role vars to role-name_var-name, but this fails with error ( incorrect <var-name>), so to avoid that, I have added the import_role.

2024-12-08 23:31 UTC, Sakethanne commented on ansible/install_os.yml
> +      ansible.builtin.uri:
it is fixed, I have used the guide from Dell while building this: https://infohub.delltechnologies.com/es-es/l/dell-poweredge-getting-started-with-redfish-ansible-modules/operating-system-deployment-56/

2024-12-08 23:31 UTC, Sakethanne commented on ansible/install_os.yml
> +    ip_address: "172.22.0.1"
updated the code to take it dynamically

2024-12-08 23:32 UTC, Sakethanne commented on ansible/install_os.yml
> +  hosts: hostbmcs
modified the hosts as well to dh1bmc and dh4bmc

2024-12-09 00:51 UTC, glimchb commented on ansible/install_os.yml
> +          iso_name: "{{ ubuntu_iso }}"
```suggestion
          iso_name: "ubuntu-22.04-autoinstall.iso"
```

2024-12-09 00:51 UTC, glimchb commented on ansible/install_os.yml
> +    ubuntu_iso: ubuntu-22.04-autoinstall.iso
remove all those vars, where do you use them?

2024-12-09 00:52 UTC, glimchb commented on ansible/install_os.yml
> +      ansible.builtin.uri:
to simplify, if this is fixed URL, just hard code it, no need to discover it, too complex

2024-12-09 00:54 UTC, glimchb commented on ansible/install_os.yml
> +        name: dellemc.openmanage.idrac_os_deployment
ok

2024-12-09 00:56 UTC, glimchb commented on ansible/install_os.yml
> +        os_version: 9
why RHEL here and UBUNTU iso below ? i understand... but you should add comment in the code... with link to PR in openmanage repo

2024-12-09 18:08 UTC, glimchb approved these changes

2024-12-09 18:08 UTC, merged